# Generated by Django 4.1.5 on 2023-01-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestOddzSys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('system', models.CharField(max_length=100)),
                ('ans1', models.CharField(max_length=100)),
                ('ans2', models.CharField(max_length=100)),
                ('ans3', models.CharField(max_length=100)),
                ('ans4', models.CharField(max_length=100)),
                ('ans5', models.CharField(max_length=100)),
                ('correct_ans', models.CharField(max_length=100)),
            ],
        ),
    ]
