# Generated by Django 4.1.5 on 2023-01-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestoddzsys',
            name='n',
        ),
    ]
