# Generated by Django 4.1.5 on 2023-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quizquestoddzsys_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestoddzsys',
            name='n',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
