# Generated by Django 4.1.5 on 2023-01-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizquestpietrsys'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestSysEra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('ERA', models.CharField(max_length=100)),
                ('ans1', models.CharField(max_length=100)),
                ('ans2', models.CharField(max_length=100)),
                ('ans3', models.CharField(max_length=100)),
                ('ans4', models.CharField(max_length=100)),
                ('ans5', models.CharField(max_length=100)),
                ('correct_ans', models.CharField(max_length=100)),
            ],
        ),
    ]
