# Generated by Django 4.1.5 on 2023-01-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizquestsysera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizQuestOddzSys',
            new_name='QuizQuestionsAbcd',
        ),
        migrations.DeleteModel(
            name='QuizQuestPietrOddz',
        ),
        migrations.DeleteModel(
            name='QuizQuestPietrSys',
        ),
        migrations.DeleteModel(
            name='QuizQuestSysEra',
        ),
        migrations.RenameField(
            model_name='quizquestionsabcd',
            old_name='system',
            new_name='suffix',
        ),
    ]
