# Generated by Django 4.1.5 on 2023-01-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_quizquestoddzsys_quizquestionsabcd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestionsabcd',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
