# Generated by Django 4.1.5 on 2023-01-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizquestionsabcd_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestionsAbcd',
        ),
    ]
