# Generated by Django 4.1.5 on 2023-01-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_quizquestionsabcd_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestionsabcd',
            name='n',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
