# Generated by Django 4.1.5 on 2023-01-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_quizquestionsabcd_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestionsabcd',
            name='n',
        ),
    ]
