# Generated by Django 4.2.6 on 2023-10-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_closedendedquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedEndedQuestion',
        ),
    ]
