# Generated by Django 4.2.6 on 2023-10-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_closedendedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestion',
        ),
    ]
