# Generated by Django 4.2.6 on 2023-10-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_closedendedquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedEndedQuestion',
        ),
    ]
