# Generated by Django 4.2.6 on 2023-12-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_closedendedquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedEndedQuestion',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionCategory',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionCorrectAnswer',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionPossibleAnswers',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionText',
        ),
    ]
