# Generated by Django 4.2.6 on 2023-12-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0018_delete_closedendedquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedQuestionPossibleAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=20)),
                ('B', models.CharField(max_length=20)),
                ('C', models.CharField(max_length=20)),
                ('D', models.CharField(max_length=20)),
                ('E', models.CharField(max_length=20)),
                ('F', models.CharField(max_length=20)),
                ('G', models.CharField(max_length=20, null=True)),
                ('H', models.CharField(max_length=20, null=True)),
                ('I', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
