# Generated by Django 4.2.6 on 2023-12-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_closedendedquestiontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category', models.CharField(max_length=200)),
            ],
        ),
    ]
