# Generated by Django 4.2.6 on 2023-12-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_closedendedquestioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedQuestionCorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
