# Generated by Django 4.2.6 on 2023-12-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_closedendedquestioncorrectanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedQuestionIsMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMulti', models.SmallIntegerField()),
            ],
        ),
    ]
