# Generated by Django 4.2.6 on 2023-12-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_closedendedquestionismulti'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_ans', to='learning.closedendedquestioncorrectanswer')),
                ('is_multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_multi_quest', to='learning.closedendedquestionismulti')),
                ('possible_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_ans', to='learning.closedendedquestionpossibleanswers')),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_cat', to='learning.closedendedquestioncategory')),
                ('question_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_txt', to='learning.closedendedquestiontext')),
            ],
        ),
    ]
