# Generated by Django 4.2.6 on 2023-12-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_rename_question_text_key_closedendedquestion_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedendedquestion',
            old_name='question_text',
            new_name='question_text_key',
        ),
    ]
