# Generated by Django 4.2.6 on 2023-12-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_rename_question_text_closedendedquestion_question_text_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedEndedQuestion',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionCategory',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionCorrectAnswer',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionIsMulti',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionPossibleAnswers',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionText',
        ),
    ]
