# Generated by Django 4.2.6 on 2023-12-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0028_delete_closedendedquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedQuestionCorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedQuestionIsMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMulti', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedQuestionPossibleAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=20)),
                ('B', models.CharField(max_length=20)),
                ('C', models.CharField(max_length=20)),
                ('D', models.CharField(max_length=20)),
                ('E', models.CharField(max_length=20)),
                ('F', models.CharField(max_length=20)),
                ('G', models.CharField(max_length=20, null=True)),
                ('H', models.CharField(max_length=20, null=True)),
                ('I', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedQuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_cat', to='learning.closedendedquestioncategory')),
                ('correct_answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_ans', to='learning.closedendedquestioncorrectanswer')),
                ('is_multi_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_multi_quest', to='learning.closedendedquestionismulti')),
                ('possible_answers_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_ans', to='learning.closedendedquestionpossibleanswers')),
                ('question_text_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_txt', to='learning.closedendedquestiontext')),
            ],
        ),
    ]
