# Generated by Django 4.2.6 on 2024-01-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenEndedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.openendedcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndedQuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndedScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_scope', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndedWrongScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_wrong_scope', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='openendedquestion',
            name='quest_txt_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.openendedquestiontext'),
        ),
        migrations.AddField(
            model_name='openendedquestion',
            name='scope_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.openendedscope'),
        ),
        migrations.AddField(
            model_name='openendedquestion',
            name='wrong_scope_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.openendedwrongscope'),
        ),
    ]
