# Generated by Django 4.2.6 on 2024-01-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_openendedcategory_openendedquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openendedquestion',
            name='category_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_cat_open', to='learning.openendedcategory'),
        ),
        migrations.AlterField(
            model_name='openendedquestion',
            name='quest_txt_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_txt_open', to='learning.openendedquestiontext'),
        ),
        migrations.AlterField(
            model_name='openendedquestion',
            name='scope_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scope_open', to='learning.openendedscope'),
        ),
        migrations.AlterField(
            model_name='openendedquestion',
            name='wrong_scope_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_wrong_scope_open', to='learning.openendedwrongscope'),
        ),
    ]
