# Generated by Django 4.2.6 on 2024-01-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_openendedcategory_openendedquestiontext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openendedquestion',
            name='category_key',
        ),
        migrations.RemoveField(
            model_name='openendedquestion',
            name='quest_txt_key',
        ),
        migrations.RemoveField(
            model_name='openendedquestion',
            name='scope_key',
        ),
        migrations.RemoveField(
            model_name='openendedquestion',
            name='wrong_scope_key',
        ),
        migrations.DeleteModel(
            name='OpenEndedCategory',
        ),
        migrations.DeleteModel(
            name='OpenEndedQuestion',
        ),
        migrations.DeleteModel(
            name='OpenEndedQuestionText',
        ),
        migrations.DeleteModel(
            name='OpenEndedScope',
        ),
        migrations.DeleteModel(
            name='OpenEndedWrongScope',
        ),
    ]
