# Generated by Django 4.2.6 on 2024-01-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_openendedcategory_openendedquestiontext_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenEndedQuestion',
        ),
        migrations.DeleteModel(
            name='OpenEndedQuestionText',
        ),
    ]
