# Generated by Django 4.2.6 on 2024-01-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0038_delete_openendedquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenEndedTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_target', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_cat_open', to='learning.openendedcategory')),
                ('scope_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scope_open', to='learning.openendedscope')),
                ('target_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_target_open', to='learning.openendedtarget')),
                ('wrong_scope_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_wrong_scope_open', to='learning.openendedwrongscope')),
            ],
        ),
    ]
