# Generated by Django 4.2.6 on 2024-01-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0039_openendedtarget_openendedquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openendedquestion',
            old_name='category_key',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='openendedquestion',
            old_name='scope_key',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='openendedquestion',
            old_name='target_key',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='openendedquestion',
            old_name='wrong_scope_key',
            new_name='wrong_scope',
        ),
    ]
