# Generated by Django 4.2.6 on 2024-01-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0040_rename_category_key_openendedquestion_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedEndedQuestion',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionCategory',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionCorrectAnswer',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionIsMulti',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionPossibleAnswers',
        ),
        migrations.DeleteModel(
            name='ClosedEndedQuestionText',
        ),
    ]
