# Generated by Django 4.2.6 on 2024-01-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0041_delete_closedendedquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedCorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_correct_answer', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedIsMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_is_multi', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedPossibleAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_possible_answers', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_target', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEndedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_cat', to='learning.closedendedcategory')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_ans', to='learning.closedendedcorrectanswer')),
                ('is_multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_multi_quest', to='learning.closedendedismulti')),
                ('possible_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_ans', to='learning.closedendedpossibleanswers')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_txt', to='learning.closedendedtarget')),
            ],
        ),
    ]
