# Generated by Django 4.2.6 on 2024-01-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0042_closedendedcategory_closedendedcorrectanswer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedEndedQuestion',
        ),
    ]
