# Generated by Django 4.2.6 on 2024-01-10 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0043_delete_closedendedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEndedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_cat', to='learning.closedendedcategory')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_ans', to='learning.closedendedcorrectanswer')),
                ('is_multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_multi_quest', to='learning.closedendedismulti')),
                ('possible_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_ans', to='learning.closedendedpossibleanswers')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_txt', to='learning.closedendedtarget')),
            ],
        ),
    ]
