# Generated by Django 4.2.6 on 2024-01-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0044_closedendedquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedEndedQuestion',
        ),
    ]
