# Generated by Django 4.2.6 on 2024-01-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0046_closedendedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_scope', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_target', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardWrongTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_wrong_scope', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcardcategory')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcardscope')),
                ('target_correct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcardtarget')),
                ('target_wrong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcardwrongtarget')),
            ],
        ),
    ]
